package jrp.blackjack;

import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import jrp.blackjack.classes.Deck;
import jrp.blackjack.classes.Card;
import jrp.blackjack.classes.Hand;

/**
 * @author James Park
 */
public class Blackjack_UI extends javax.swing.JFrame {

    /**
     * Creates new form Blackjack_UI
     */
    public Blackjack_UI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnDealHand = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblPlayerScore = new javax.swing.JLabel();
        imgDealerCardTwo = new javax.swing.JLabel();
        imgDealerCardOne = new javax.swing.JLabel();
        btnHit = new javax.swing.JButton();
        btnStick = new javax.swing.JButton();
        btnDouble = new javax.swing.JButton();
        imgPlayerCardThree = new javax.swing.JLabel();
        imgPlayerCardFour = new javax.swing.JLabel();
        imgPlayerCardOne = new javax.swing.JLabel();
        imgPlayerCardTwo = new javax.swing.JLabel();
        imgPlayerCardSix = new javax.swing.JLabel();
        imgPlayerCardFive = new javax.swing.JLabel();
        imgDealerCardThree = new javax.swing.JLabel();
        imgDealerCardFour = new javax.swing.JLabel();
        imgDealerCardSix = new javax.swing.JLabel();
        imgDealerCardFive = new javax.swing.JLabel();
        lblDealerScore = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Blackjack");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setAutoscrolls(true);

        btnDealHand.setBackground(new java.awt.Color(153, 153, 153));
        btnDealHand.setForeground(new java.awt.Color(0, 0, 0));
        btnDealHand.setText("Deal");
        btnDealHand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDealHandActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Score:");

        imgDealerCardTwo.setBackground(new java.awt.Color(204, 204, 204));
        imgDealerCardTwo.setForeground(new java.awt.Color(0, 0, 0));
        imgDealerCardTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDealerCardTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgDealerCardOne.setForeground(new java.awt.Color(0, 0, 0));
        imgDealerCardOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDealerCardOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnHit.setBackground(new java.awt.Color(153, 153, 153));
        btnHit.setForeground(new java.awt.Color(0, 0, 0));
        btnHit.setText("Hit");
        btnHit.setEnabled(false);
        btnHit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitActionPerformed(evt);
            }
        });

        btnStick.setBackground(new java.awt.Color(153, 153, 153));
        btnStick.setForeground(new java.awt.Color(0, 0, 0));
        btnStick.setText("Stick");
        btnStick.setEnabled(false);
        btnStick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStickActionPerformed(evt);
            }
        });

        btnDouble.setBackground(new java.awt.Color(153, 153, 153));
        btnDouble.setForeground(new java.awt.Color(0, 0, 0));
        btnDouble.setText("Double");
        btnDouble.setEnabled(false);

        imgPlayerCardThree.setForeground(new java.awt.Color(0, 0, 0));
        imgPlayerCardThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPlayerCardThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgPlayerCardFour.setForeground(new java.awt.Color(0, 0, 0));
        imgPlayerCardFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPlayerCardFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgPlayerCardOne.setForeground(new java.awt.Color(0, 0, 0));
        imgPlayerCardOne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPlayerCardOne.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgPlayerCardTwo.setBackground(new java.awt.Color(204, 204, 204));
        imgPlayerCardTwo.setForeground(new java.awt.Color(0, 0, 0));
        imgPlayerCardTwo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPlayerCardTwo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgPlayerCardSix.setForeground(new java.awt.Color(0, 0, 0));
        imgPlayerCardSix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPlayerCardSix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgPlayerCardFive.setForeground(new java.awt.Color(0, 0, 0));
        imgPlayerCardFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgPlayerCardFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgDealerCardThree.setForeground(new java.awt.Color(0, 0, 0));
        imgDealerCardThree.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDealerCardThree.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgDealerCardFour.setBackground(new java.awt.Color(204, 204, 204));
        imgDealerCardFour.setForeground(new java.awt.Color(0, 0, 0));
        imgDealerCardFour.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDealerCardFour.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgDealerCardSix.setForeground(new java.awt.Color(0, 0, 0));
        imgDealerCardSix.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDealerCardSix.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        imgDealerCardFive.setBackground(new java.awt.Color(204, 204, 204));
        imgDealerCardFive.setForeground(new java.awt.Color(0, 0, 0));
        imgDealerCardFive.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgDealerCardFive.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Dealer Score");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(imgPlayerCardOne, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgPlayerCardTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPlayerCardThree, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPlayerCardFour, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPlayerCardFive, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imgPlayerCardSix, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStick, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDouble, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDealHand, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgDealerCardSix, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgDealerCardFive, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgDealerCardFour, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgDealerCardThree, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgDealerCardTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgDealerCardOne, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDealerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(imgPlayerCardFive, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(lblPlayerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblDealerScore, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(imgDealerCardFive, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(imgPlayerCardFour, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel1))
                                    .addComponent(imgPlayerCardTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(61, 61, 61))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgDealerCardOne, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(imgDealerCardTwo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(imgDealerCardThree, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(imgDealerCardFour, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37)
                        .addComponent(imgPlayerCardSix, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(imgDealerCardSix, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(imgPlayerCardThree, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(imgPlayerCardOne, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnDealHand)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDouble)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStick)))
                        .addGap(35, 35, 35))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

//========================GAME DECK & HAND======================================
    private final Deck gameDeck = new Deck();
    private Hand playerHand = new Hand();
    private Hand dealerHand = new Hand();
//==============================================================================

//===============================AVAILABLE CARD SLOTS===========================
    private final ArrayList<JLabel> playerSpots = new ArrayList<>();
    private final ArrayList<JLabel> dealerSpots = new ArrayList<>();
//==============================================================================

//================================METHODS=======================================
    public void setImage(Card card, JLabel img, boolean dealersFirstCard) {

        img.setText(null);
        String filename;

        if (!dealersFirstCard) {
            filename = card.getCard_file_path();
        } else {
            filename = "card_back.png";
        }
        ImageIcon imageIcon = new javax.swing.ImageIcon(
                getClass().getResource("Images\\" + filename)
        );
        Image image = imageIcon.getImage();
        Image newimg = image.getScaledInstance(
                img.getWidth(),
                img.getHeight(),
                java.awt.Image.SCALE_SMOOTH
        );
        img.setIcon(new ImageIcon(newimg));
    }

    public void endGame(boolean win) {

        String message;
        String message2;
        if (win) {
            message = "You Won";
            message2 = "Play Again?";
        } else {
            message = "You Lose";
            message2 = "Play Again?";
        }

        JLabel label_endgame_message = new JLabel(message);
        JLabel label_endgame_message2 = new JLabel(message2);

        Object[] endgame_GUI_Element = {label_endgame_message, label_endgame_message2};

        int userInteraction = JOptionPane.showConfirmDialog(
                null,
                endgame_GUI_Element,
                "Game Over",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (userInteraction == JOptionPane.YES_OPTION) {
            newGame();
        } else {
            JOptionPane.showMessageDialog(null, "Thanks for playing");
            System.exit(0);
        }

    }

    public void newGame() {
        Deck.shuffleDeck(gameDeck);
        playerHand = new Hand();
        dealerHand = new Hand();
        btnDealHand.setEnabled(true);
        btnHit.setEnabled(false);
        btnDouble.setEnabled(false);
        btnStick.setEnabled(false);
        
        lblPlayerScore.setText("");
        lblDealerScore.setText("");
        
        imgPlayerCardOne.setIcon(null);
        imgPlayerCardTwo.setIcon(null);
        imgPlayerCardThree.setIcon(null);
        imgPlayerCardFour.setIcon(null);
        imgPlayerCardFive.setIcon(null);
        imgPlayerCardSix.setIcon(null);

        imgDealerCardOne.setIcon(null);
        imgDealerCardTwo.setIcon(null);
        imgDealerCardThree.setIcon(null);
        imgDealerCardFour.setIcon(null);
        imgDealerCardFive.setIcon(null);
        imgDealerCardSix.setIcon(null);
    }
//==============================================================================    


    private void btnDealHandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDealHandActionPerformed

        playerHand = new Hand();
        dealerHand = new Hand();

        btnDealHand.setEnabled(false);
        btnHit.setEnabled(true);
        btnDouble.setEnabled(true);
        btnStick.setEnabled(true);

        for (int i = 1; i < 5; i++) {
            if (i % 2 == 0) {
                Card cardDrawn = Deck.drawCardFromDeck(gameDeck);
                playerHand.addToScore(cardDrawn);
                playerHand.addCardToHand(cardDrawn);
                setImage(playerHand.getHand().get(playerHand.getHand().size() - 1), playerSpots.get(playerHand.getHitCount()), false);
                playerHand.incrementHitCount();

            } else {
                Card cardDrawn = Deck.drawCardFromDeck(gameDeck);
                dealerHand.addToScore(cardDrawn);
                dealerHand.addCardToHand(cardDrawn);

                if (dealerHand.getHitCount() == 0) {

                    setImage(dealerHand.getHand().get(0), imgDealerCardOne, true);
                    dealerHand.incrementHitCount();

                } else {
                    setImage(dealerHand.getHand().get(dealerHand.getHand().size() - 1), dealerSpots.get(dealerHand.getHitCount()), false);
                    dealerHand.incrementHitCount();
                }
            }
        }
        lblPlayerScore.setText("" + playerHand.getScore());
        lblDealerScore.setText("" + dealerHand.getHand().get(1).getCard_value());

        if (playerHand.getScore() >= 21) {
            endGame(true);
        }
    }//GEN-LAST:event_btnDealHandActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        playerSpots.add(imgPlayerCardOne);
        playerSpots.add(imgPlayerCardTwo);
        playerSpots.add(imgPlayerCardThree);
        playerSpots.add(imgPlayerCardFour);
        playerSpots.add(imgPlayerCardFive);
        playerSpots.add(imgPlayerCardSix);

        dealerSpots.add(imgDealerCardOne);
        dealerSpots.add(imgDealerCardTwo);
        dealerSpots.add(imgDealerCardThree);
        dealerSpots.add(imgDealerCardFour);
        dealerSpots.add(imgDealerCardFive);
        dealerSpots.add(imgDealerCardSix);
    }//GEN-LAST:event_formWindowOpened

    private void btnHitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitActionPerformed

        Card cardDrawn = Deck.drawCardFromDeck(gameDeck);
        playerHand.addToScore(cardDrawn);
        playerHand.addCardToHand(cardDrawn);

        setImage(playerHand.getHand().get(playerHand.getHand().size() - 1), playerSpots.get(playerHand.getHitCount()), false);

        lblPlayerScore.setText("" + playerHand.getScore());
        playerHand.incrementHitCount();
        
        if (playerHand.getScore() > 21) {
            endGame(false);
        }
    }//GEN-LAST:event_btnHitActionPerformed

    private void btnStickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStickActionPerformed
        btnHit.setEnabled(false);
        btnDouble.setEnabled(false);

        if (dealerHand.getHitCount() < 3) {

            setImage(dealerHand.getHand().get(0), imgDealerCardOne, false);
            lblDealerScore.setText("" + dealerHand.getScore());
        }

        while (dealerHand.getScore() < 21) {

            if (dealerHand.getScore() > 17) {
                break;
            }
            Card cardDrawn = Deck.drawCardFromDeck(gameDeck);
            dealerHand.addToScore(cardDrawn);
            dealerHand.addCardToHand(cardDrawn);

            setImage(dealerHand.getHand().get(dealerHand.getHand().size() - 1), dealerSpots.get(dealerHand.getHitCount()), false);
            lblDealerScore.setText("" + dealerHand.getScore());

            dealerHand.incrementHitCount();
        }

        int pScore = playerHand.getScore();
        int dScore = dealerHand.getScore();

        if (pScore <= 21 && dScore > 21) {
            endGame(true);
        } else if (pScore > dScore && pScore <= 21) {
            endGame(true);
        } else {
            endGame(false);
        }

    }//GEN-LAST:event_btnStickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Blackjack_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Blackjack_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Blackjack_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Blackjack_UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Blackjack_UI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDealHand;
    private javax.swing.JButton btnDouble;
    private javax.swing.JButton btnHit;
    private javax.swing.JButton btnStick;
    private javax.swing.JLabel imgDealerCardFive;
    private javax.swing.JLabel imgDealerCardFour;
    private javax.swing.JLabel imgDealerCardOne;
    private javax.swing.JLabel imgDealerCardSix;
    private javax.swing.JLabel imgDealerCardThree;
    private javax.swing.JLabel imgDealerCardTwo;
    private javax.swing.JLabel imgPlayerCardFive;
    private javax.swing.JLabel imgPlayerCardFour;
    private javax.swing.JLabel imgPlayerCardOne;
    private javax.swing.JLabel imgPlayerCardSix;
    private javax.swing.JLabel imgPlayerCardThree;
    private javax.swing.JLabel imgPlayerCardTwo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDealerScore;
    private javax.swing.JLabel lblPlayerScore;
    // End of variables declaration//GEN-END:variables
}
